version: '3.8'

services:
  backend:
    build: 
      context: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env.backend
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/models
    volumes:
      - ./server:/app
      - ./model:/models
    networks:
      - cvembed-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./client
    ports:
      - "3000:8080"
    env_file:
      - .env.frontend
    depends_on:
      - backend
    networks:
      - cvembed-network
    restart: unless-stopped

networks:
  cvembed-network:
    driver: bridge